// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/deserialization/src/builtins.proto

package kotlin.reflect.jvm.internal.impl.serialization.builtins;

public final class BuiltInsProtoBuf {
  private BuiltInsProtoBuf() {}
  public static void registerAllExtensions(
      kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite registry) {
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.packageFqName);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.classAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.constructorAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.functionAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.propertyAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.compileTimeValue);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.enumEntryAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.parameterAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.typeAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.typeParameterAnnotation);
  }
  public interface BuiltInsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltIns)
      kotlin.reflect.jvm.internal.impl.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
     */
    boolean hasStrings();
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
     */
    kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable getStrings();

    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
     */
    boolean hasQualifiedNames();
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
     */
    kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable getQualifiedNames();

    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
     */
    boolean hasPackage();
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
     */
    kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package getPackage();

    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class> 
        getClass_List();
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class getClass_(int index);
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    int getClass_Count();
  }
  /**
   * Protobuf type {@code kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltIns}
   */
  public static final class BuiltIns extends
      kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltIns)
      BuiltInsOrBuilder {
    // Use BuiltIns.newBuilder() to construct.
    private BuiltIns(kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BuiltIns(boolean noInit) { this.unknownFields = kotlin.reflect.jvm.internal.impl.protobuf.ByteString.EMPTY;}

    private static final BuiltIns defaultInstance;
    public static BuiltIns getDefaultInstance() {
      return defaultInstance;
    }

    public BuiltIns getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final kotlin.reflect.jvm.internal.impl.protobuf.ByteString unknownFields;
    private BuiltIns(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      kotlin.reflect.jvm.internal.impl.protobuf.ByteString.Output unknownFieldsOutput =
          kotlin.reflect.jvm.internal.impl.protobuf.ByteString.newOutput();
      kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = strings_.toBuilder();
              }
              strings_ = input.readMessage(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(strings_);
                strings_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = qualifiedNames_.toBuilder();
              }
              qualifiedNames_ = input.readMessage(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(qualifiedNames_);
                qualifiedNames_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = package_.toBuilder();
              }
              package_ = input.readMessage(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(package_);
                package_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                class__ = new java.util.ArrayList<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class>();
                mutable_bitField0_ |= 0x00000008;
              }
              class__.add(input.readMessage(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          class__ = java.util.Collections.unmodifiableList(class__);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static kotlin.reflect.jvm.internal.impl.protobuf.Parser<BuiltIns> PARSER =
        new kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser<BuiltIns>() {
      public BuiltIns parsePartialFrom(
          kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
          kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
          throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
        return new BuiltIns(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public kotlin.reflect.jvm.internal.impl.protobuf.Parser<BuiltIns> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STRINGS_FIELD_NUMBER = 1;
    private kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable strings_;
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
     */
    public boolean hasStrings() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
     */
    public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable getStrings() {
      return strings_;
    }

    public static final int QUALIFIED_NAMES_FIELD_NUMBER = 2;
    private kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable qualifiedNames_;
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
     */
    public boolean hasQualifiedNames() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
     */
    public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable getQualifiedNames() {
      return qualifiedNames_;
    }

    public static final int PACKAGE_FIELD_NUMBER = 3;
    private kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package package_;
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
     */
    public boolean hasPackage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
     */
    public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package getPackage() {
      return package_;
    }

    public static final int CLASS_FIELD_NUMBER = 4;
    private java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class> class__;
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    public java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class> getClass_List() {
      return class__;
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    public java.util.List<? extends kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.ClassOrBuilder> 
        getClass_OrBuilderList() {
      return class__;
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    public int getClass_Count() {
      return class__.size();
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class getClass_(int index) {
      return class__.get(index);
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
     */
    public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.ClassOrBuilder getClass_OrBuilder(
        int index) {
      return class__.get(index);
    }

    private void initFields() {
      strings_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.getDefaultInstance();
      qualifiedNames_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.getDefaultInstance();
      package_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.getDefaultInstance();
      class__ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasQualifiedNames()) {
        if (!getQualifiedNames().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPackage()) {
        if (!getPackage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getClass_Count(); i++) {
        if (!getClass_(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, strings_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, qualifiedNames_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, package_);
      }
      for (int i = 0; i < class__.size(); i++) {
        output.writeMessage(4, class__.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream
          .computeMessageSize(1, strings_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream
          .computeMessageSize(2, qualifiedNames_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream
          .computeMessageSize(3, package_);
      }
      for (int i = 0; i < class__.size(); i++) {
        size += kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream
          .computeMessageSize(4, class__.get(i));
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString data)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString data,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(byte[] data)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(
        byte[] data,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(
        java.io.InputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseDelimitedFrom(
        java.io.InputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltIns}
     */
    public static final class Builder extends
        kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.Builder<
          kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltIns)
        kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltInsOrBuilder {
      // Construct using kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        strings_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        qualifiedNames_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        package_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000004);
        class__ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns getDefaultInstanceForType() {
        return kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns.getDefaultInstance();
      }

      public kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns build() {
        kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns buildPartial() {
        kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns result = new kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strings_ = strings_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.qualifiedNames_ = qualifiedNames_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.package_ = package_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          class__ = java.util.Collections.unmodifiableList(class__);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.class__ = class__;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns other) {
        if (other == kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns.getDefaultInstance()) return this;
        if (other.hasStrings()) {
          mergeStrings(other.getStrings());
        }
        if (other.hasQualifiedNames()) {
          mergeQualifiedNames(other.getQualifiedNames());
        }
        if (other.hasPackage()) {
          mergePackage(other.getPackage());
        }
        if (!other.class__.isEmpty()) {
          if (class__.isEmpty()) {
            class__ = other.class__;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureClass_IsMutable();
            class__.addAll(other.class__);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (hasQualifiedNames()) {
          if (!getQualifiedNames().isInitialized()) {
            
            return false;
          }
        }
        if (hasPackage()) {
          if (!getPackage().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getClass_Count(); i++) {
          if (!getClass_(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
          kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.BuiltIns) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable strings_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.getDefaultInstance();
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
       */
      public boolean hasStrings() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
       */
      public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable getStrings() {
        return strings_;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
       */
      public Builder setStrings(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable value) {
        if (value == null) {
          throw new NullPointerException();
        }
        strings_ = value;

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
       */
      public Builder setStrings(
          kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.Builder builderForValue) {
        strings_ = builderForValue.build();

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
       */
      public Builder mergeStrings(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            strings_ != kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.getDefaultInstance()) {
          strings_ =
            kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.newBuilder(strings_).mergeFrom(value).buildPartial();
        } else {
          strings_ = value;
        }

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.StringTable strings = 1;</code>
       */
      public Builder clearStrings() {
        strings_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.StringTable.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      private kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable qualifiedNames_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.getDefaultInstance();
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
       */
      public boolean hasQualifiedNames() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
       */
      public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable getQualifiedNames() {
        return qualifiedNames_;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
       */
      public Builder setQualifiedNames(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable value) {
        if (value == null) {
          throw new NullPointerException();
        }
        qualifiedNames_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
       */
      public Builder setQualifiedNames(
          kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.Builder builderForValue) {
        qualifiedNames_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
       */
      public Builder mergeQualifiedNames(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            qualifiedNames_ != kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.getDefaultInstance()) {
          qualifiedNames_ =
            kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.newBuilder(qualifiedNames_).mergeFrom(value).buildPartial();
        } else {
          qualifiedNames_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.QualifiedNameTable qualified_names = 2;</code>
       */
      public Builder clearQualifiedNames() {
        qualifiedNames_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.QualifiedNameTable.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      private kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package package_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.getDefaultInstance();
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
       */
      public boolean hasPackage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
       */
      public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package getPackage() {
        return package_;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
       */
      public Builder setPackage(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package value) {
        if (value == null) {
          throw new NullPointerException();
        }
        package_ = value;

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
       */
      public Builder setPackage(
          kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.Builder builderForValue) {
        package_ = builderForValue.build();

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
       */
      public Builder mergePackage(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package value) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            package_ != kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.getDefaultInstance()) {
          package_ =
            kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.newBuilder(package_).mergeFrom(value).buildPartial();
        } else {
          package_ = value;
        }

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .kotlin.reflect.jvm.internal.impl.serialization.Package package = 3;</code>
       */
      public Builder clearPackage() {
        package_ = kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      private java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class> class__ =
        java.util.Collections.emptyList();
      private void ensureClass_IsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          class__ = new java.util.ArrayList<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class>(class__);
          bitField0_ |= 0x00000008;
         }
      }

      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class> getClass_List() {
        return java.util.Collections.unmodifiableList(class__);
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public int getClass_Count() {
        return class__.size();
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class getClass_(int index) {
        return class__.get(index);
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder setClass_(
          int index, kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClass_IsMutable();
        class__.set(index, value);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder setClass_(
          int index, kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class.Builder builderForValue) {
        ensureClass_IsMutable();
        class__.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder addClass_(kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClass_IsMutable();
        class__.add(value);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder addClass_(
          int index, kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClass_IsMutable();
        class__.add(index, value);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder addClass_(
          kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class.Builder builderForValue) {
        ensureClass_IsMutable();
        class__.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder addClass_(
          int index, kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class.Builder builderForValue) {
        ensureClass_IsMutable();
        class__.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder addAllClass_(
          java.lang.Iterable<? extends kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class> values) {
        ensureClass_IsMutable();
        kotlin.reflect.jvm.internal.impl.protobuf.AbstractMessageLite.Builder.addAll(
            values, class__);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder clearClass_() {
        class__ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.Class class = 4;</code>
       */
      public Builder removeClass_(int index) {
        ensureClass_IsMutable();
        class__.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltIns)
    }

    static {
      defaultInstance = new BuiltIns(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltIns)
  }

  public static final int PACKAGE_FQ_NAME_FIELD_NUMBER = 151;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Package { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package,
      java.lang.Integer> packageFqName = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.getDefaultInstance(),
        0,
        null,
        null,
        151,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.INT32,
        java.lang.Integer.class);
  public static final int CLASS_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Class { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> classAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int CONSTRUCTOR_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Constructor { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Constructor,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> constructorAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Constructor.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int FUNCTION_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Function { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Function,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> functionAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Function.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int PROPERTY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Property { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> propertyAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int COMPILE_TIME_VALUE_FIELD_NUMBER = 151;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Property { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property,
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value> compileTimeValue = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value.getDefaultInstance(),
        null,
        151,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value.class);
  public static final int ENUM_ENTRY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.EnumEntry { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.EnumEntry,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> enumEntryAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.EnumEntry.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.ValueParameter { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.ValueParameter,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> parameterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.ValueParameter.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int TYPE_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Type { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Type,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> typeAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Type.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int TYPE_PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.TypeParameter { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.TypeParameter,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> typeParameterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.TypeParameter.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}