// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/descriptor.loader.java/src/jvm_package_table.proto

package kotlin.reflect.jvm.internal.impl.serialization.jvm;

public final class JvmPackageTable {
  private JvmPackageTable() {}
  public static void registerAllExtensions(
      kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PackageTableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageTable)
      kotlin.reflect.jvm.internal.impl.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    java.util.List<kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts> 
        getPackagePartsList();
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts getPackageParts(int index);
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    int getPackagePartsCount();
  }
  /**
   * Protobuf type {@code kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageTable}
   */
  public static final class PackageTable extends
      kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageTable)
      PackageTableOrBuilder {
    // Use PackageTable.newBuilder() to construct.
    private PackageTable(kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PackageTable(boolean noInit) { this.unknownFields = kotlin.reflect.jvm.internal.impl.protobuf.ByteString.EMPTY;}

    private static final PackageTable defaultInstance;
    public static PackageTable getDefaultInstance() {
      return defaultInstance;
    }

    public PackageTable getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final kotlin.reflect.jvm.internal.impl.protobuf.ByteString unknownFields;
    private PackageTable(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      kotlin.reflect.jvm.internal.impl.protobuf.ByteString.Output unknownFieldsOutput =
          kotlin.reflect.jvm.internal.impl.protobuf.ByteString.newOutput();
      kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                packageParts_ = new java.util.ArrayList<kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts>();
                mutable_bitField0_ |= 0x00000001;
              }
              packageParts_.add(input.readMessage(kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          packageParts_ = java.util.Collections.unmodifiableList(packageParts_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static kotlin.reflect.jvm.internal.impl.protobuf.Parser<PackageTable> PARSER =
        new kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser<PackageTable>() {
      public PackageTable parsePartialFrom(
          kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
          kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
          throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
        return new PackageTable(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public kotlin.reflect.jvm.internal.impl.protobuf.Parser<PackageTable> getParserForType() {
      return PARSER;
    }

    public static final int PACKAGE_PARTS_FIELD_NUMBER = 1;
    private java.util.List<kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts> packageParts_;
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    public java.util.List<kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts> getPackagePartsList() {
      return packageParts_;
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    public java.util.List<? extends kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackagePartsOrBuilder> 
        getPackagePartsOrBuilderList() {
      return packageParts_;
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    public int getPackagePartsCount() {
      return packageParts_.size();
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts getPackageParts(int index) {
      return packageParts_.get(index);
    }
    /**
     * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
     */
    public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackagePartsOrBuilder getPackagePartsOrBuilder(
        int index) {
      return packageParts_.get(index);
    }

    private void initFields() {
      packageParts_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPackagePartsCount(); i++) {
        if (!getPackageParts(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < packageParts_.size(); i++) {
        output.writeMessage(1, packageParts_.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < packageParts_.size(); i++) {
        size += kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream
          .computeMessageSize(1, packageParts_.get(i));
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString data)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString data,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(byte[] data)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(
        byte[] data,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(
        java.io.InputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseDelimitedFrom(
        java.io.InputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageTable}
     */
    public static final class Builder extends
        kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.Builder<
          kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageTable)
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTableOrBuilder {
      // Construct using kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        packageParts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable getDefaultInstanceForType() {
        return kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable.getDefaultInstance();
      }

      public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable build() {
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable buildPartial() {
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable result = new kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          packageParts_ = java.util.Collections.unmodifiableList(packageParts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.packageParts_ = packageParts_;
        return result;
      }

      public Builder mergeFrom(kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable other) {
        if (other == kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable.getDefaultInstance()) return this;
        if (!other.packageParts_.isEmpty()) {
          if (packageParts_.isEmpty()) {
            packageParts_ = other.packageParts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePackagePartsIsMutable();
            packageParts_.addAll(other.packageParts_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPackagePartsCount(); i++) {
          if (!getPackageParts(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
          kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageTable) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts> packageParts_ =
        java.util.Collections.emptyList();
      private void ensurePackagePartsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          packageParts_ = new java.util.ArrayList<kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts>(packageParts_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public java.util.List<kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts> getPackagePartsList() {
        return java.util.Collections.unmodifiableList(packageParts_);
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public int getPackagePartsCount() {
        return packageParts_.size();
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts getPackageParts(int index) {
        return packageParts_.get(index);
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder setPackageParts(
          int index, kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackagePartsIsMutable();
        packageParts_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder setPackageParts(
          int index, kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts.Builder builderForValue) {
        ensurePackagePartsIsMutable();
        packageParts_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder addPackageParts(kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackagePartsIsMutable();
        packageParts_.add(value);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder addPackageParts(
          int index, kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackagePartsIsMutable();
        packageParts_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder addPackageParts(
          kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts.Builder builderForValue) {
        ensurePackagePartsIsMutable();
        packageParts_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder addPackageParts(
          int index, kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts.Builder builderForValue) {
        ensurePackagePartsIsMutable();
        packageParts_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder addAllPackageParts(
          java.lang.Iterable<? extends kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts> values) {
        ensurePackagePartsIsMutable();
        kotlin.reflect.jvm.internal.impl.protobuf.AbstractMessageLite.Builder.addAll(
            values, packageParts_);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder clearPackageParts() {
        packageParts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts package_parts = 1;</code>
       */
      public Builder removePackageParts(int index) {
        ensurePackagePartsIsMutable();
        packageParts_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageTable)
    }

    static {
      defaultInstance = new PackageTable(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageTable)
  }

  public interface PackagePartsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts)
      kotlin.reflect.jvm.internal.impl.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string package_fq_name = 1;</code>
     */
    boolean hasPackageFqName();
    /**
     * <code>required string package_fq_name = 1;</code>
     */
    java.lang.String getPackageFqName();
    /**
     * <code>required string package_fq_name = 1;</code>
     */
    kotlin.reflect.jvm.internal.impl.protobuf.ByteString
        getPackageFqNameBytes();

    /**
     * <code>repeated string class_name = 2;</code>
     */
    kotlin.reflect.jvm.internal.impl.protobuf.ProtocolStringList
        getClassNameList();
    /**
     * <code>repeated string class_name = 2;</code>
     */
    int getClassNameCount();
    /**
     * <code>repeated string class_name = 2;</code>
     */
    java.lang.String getClassName(int index);
    /**
     * <code>repeated string class_name = 2;</code>
     */
    kotlin.reflect.jvm.internal.impl.protobuf.ByteString
        getClassNameBytes(int index);
  }
  /**
   * Protobuf type {@code kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts}
   */
  public static final class PackageParts extends
      kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts)
      PackagePartsOrBuilder {
    // Use PackageParts.newBuilder() to construct.
    private PackageParts(kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PackageParts(boolean noInit) { this.unknownFields = kotlin.reflect.jvm.internal.impl.protobuf.ByteString.EMPTY;}

    private static final PackageParts defaultInstance;
    public static PackageParts getDefaultInstance() {
      return defaultInstance;
    }

    public PackageParts getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final kotlin.reflect.jvm.internal.impl.protobuf.ByteString unknownFields;
    private PackageParts(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      kotlin.reflect.jvm.internal.impl.protobuf.ByteString.Output unknownFieldsOutput =
          kotlin.reflect.jvm.internal.impl.protobuf.ByteString.newOutput();
      kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              kotlin.reflect.jvm.internal.impl.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              packageFqName_ = bs;
              break;
            }
            case 18: {
              kotlin.reflect.jvm.internal.impl.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                className_ = new kotlin.reflect.jvm.internal.impl.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              className_.add(bs);
              break;
            }
          }
        }
      } catch (kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          className_ = className_.getUnmodifiableView();
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static kotlin.reflect.jvm.internal.impl.protobuf.Parser<PackageParts> PARSER =
        new kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser<PackageParts>() {
      public PackageParts parsePartialFrom(
          kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
          kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
          throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
        return new PackageParts(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public kotlin.reflect.jvm.internal.impl.protobuf.Parser<PackageParts> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PACKAGE_FQ_NAME_FIELD_NUMBER = 1;
    private java.lang.Object packageFqName_;
    /**
     * <code>required string package_fq_name = 1;</code>
     */
    public boolean hasPackageFqName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string package_fq_name = 1;</code>
     */
    public java.lang.String getPackageFqName() {
      java.lang.Object ref = packageFqName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString bs = 
            (kotlin.reflect.jvm.internal.impl.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageFqName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string package_fq_name = 1;</code>
     */
    public kotlin.reflect.jvm.internal.impl.protobuf.ByteString
        getPackageFqNameBytes() {
      java.lang.Object ref = packageFqName_;
      if (ref instanceof java.lang.String) {
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString b = 
            kotlin.reflect.jvm.internal.impl.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageFqName_ = b;
        return b;
      } else {
        return (kotlin.reflect.jvm.internal.impl.protobuf.ByteString) ref;
      }
    }

    public static final int CLASS_NAME_FIELD_NUMBER = 2;
    private kotlin.reflect.jvm.internal.impl.protobuf.LazyStringList className_;
    /**
     * <code>repeated string class_name = 2;</code>
     */
    public kotlin.reflect.jvm.internal.impl.protobuf.ProtocolStringList
        getClassNameList() {
      return className_;
    }
    /**
     * <code>repeated string class_name = 2;</code>
     */
    public int getClassNameCount() {
      return className_.size();
    }
    /**
     * <code>repeated string class_name = 2;</code>
     */
    public java.lang.String getClassName(int index) {
      return className_.get(index);
    }
    /**
     * <code>repeated string class_name = 2;</code>
     */
    public kotlin.reflect.jvm.internal.impl.protobuf.ByteString
        getClassNameBytes(int index) {
      return className_.getByteString(index);
    }

    private void initFields() {
      packageFqName_ = "";
      className_ = kotlin.reflect.jvm.internal.impl.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackageFqName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPackageFqNameBytes());
      }
      for (int i = 0; i < className_.size(); i++) {
        output.writeBytes(2, className_.getByteString(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream
          .computeBytesSize(1, getPackageFqNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < className_.size(); i++) {
          dataSize += kotlin.reflect.jvm.internal.impl.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(className_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getClassNameList().size();
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString data)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.ByteString data,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(byte[] data)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(
        byte[] data,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(
        java.io.InputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseDelimitedFrom(
        java.io.InputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parseFrom(
        kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
        kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts}
     */
    public static final class Builder extends
        kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.Builder<
          kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts)
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackagePartsOrBuilder {
      // Construct using kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        packageFqName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        className_ = kotlin.reflect.jvm.internal.impl.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts getDefaultInstanceForType() {
        return kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts.getDefaultInstance();
      }

      public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts build() {
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts buildPartial() {
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts result = new kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packageFqName_ = packageFqName_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          className_ = className_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.className_ = className_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts other) {
        if (other == kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts.getDefaultInstance()) return this;
        if (other.hasPackageFqName()) {
          bitField0_ |= 0x00000001;
          packageFqName_ = other.packageFqName_;
          
        }
        if (!other.className_.isEmpty()) {
          if (className_.isEmpty()) {
            className_ = other.className_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureClassNameIsMutable();
            className_.addAll(other.className_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPackageFqName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream input,
          kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (kotlin.reflect.jvm.internal.impl.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kotlin.reflect.jvm.internal.impl.serialization.jvm.JvmPackageTable.PackageParts) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object packageFqName_ = "";
      /**
       * <code>required string package_fq_name = 1;</code>
       */
      public boolean hasPackageFqName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string package_fq_name = 1;</code>
       */
      public java.lang.String getPackageFqName() {
        java.lang.Object ref = packageFqName_;
        if (!(ref instanceof java.lang.String)) {
          kotlin.reflect.jvm.internal.impl.protobuf.ByteString bs =
              (kotlin.reflect.jvm.internal.impl.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packageFqName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string package_fq_name = 1;</code>
       */
      public kotlin.reflect.jvm.internal.impl.protobuf.ByteString
          getPackageFqNameBytes() {
        java.lang.Object ref = packageFqName_;
        if (ref instanceof String) {
          kotlin.reflect.jvm.internal.impl.protobuf.ByteString b = 
              kotlin.reflect.jvm.internal.impl.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageFqName_ = b;
          return b;
        } else {
          return (kotlin.reflect.jvm.internal.impl.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string package_fq_name = 1;</code>
       */
      public Builder setPackageFqName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageFqName_ = value;
        
        return this;
      }
      /**
       * <code>required string package_fq_name = 1;</code>
       */
      public Builder clearPackageFqName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageFqName_ = getDefaultInstance().getPackageFqName();
        
        return this;
      }
      /**
       * <code>required string package_fq_name = 1;</code>
       */
      public Builder setPackageFqNameBytes(
          kotlin.reflect.jvm.internal.impl.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageFqName_ = value;
        
        return this;
      }

      private kotlin.reflect.jvm.internal.impl.protobuf.LazyStringList className_ = kotlin.reflect.jvm.internal.impl.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          className_ = new kotlin.reflect.jvm.internal.impl.protobuf.LazyStringArrayList(className_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public kotlin.reflect.jvm.internal.impl.protobuf.ProtocolStringList
          getClassNameList() {
        return className_.getUnmodifiableView();
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public int getClassNameCount() {
        return className_.size();
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public java.lang.String getClassName(int index) {
        return className_.get(index);
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public kotlin.reflect.jvm.internal.impl.protobuf.ByteString
          getClassNameBytes(int index) {
        return className_.getByteString(index);
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public Builder setClassName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameIsMutable();
        className_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public Builder addClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameIsMutable();
        className_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public Builder addAllClassName(
          java.lang.Iterable<java.lang.String> values) {
        ensureClassNameIsMutable();
        kotlin.reflect.jvm.internal.impl.protobuf.AbstractMessageLite.Builder.addAll(
            values, className_);
        
        return this;
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public Builder clearClassName() {
        className_ = kotlin.reflect.jvm.internal.impl.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }
      /**
       * <code>repeated string class_name = 2;</code>
       */
      public Builder addClassNameBytes(
          kotlin.reflect.jvm.internal.impl.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameIsMutable();
        className_.add(value);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts)
    }

    static {
      defaultInstance = new PackageParts(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:kotlin.reflect.jvm.internal.impl.serialization.jvm.PackageParts)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}